apiVersion: v1
kind: Service
metadata:
  name: trend-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  type: LoadBalancer
  selector:
    app: trend-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
